/**
 * Generated by openapi-typescript. DO NOT EDIT BY HAND.
 * Run `make types` to regenerate after backend API changes.
 *
 * This file is a placeholder shipped so TypeScript compiles on `git clone`.
 * The real generated content lands once `make openapi && make types` runs.
 */

export type paths = Record<string, never>;
export type components = { schemas: Record<string, never> };
export type operations = Record<string, never>;
